/* =====================================================
   creamos la TABLA de PAIS
   ===================================================== */
CREATE TABLE PAIS (
    id_pais NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(20) NOT NULL,

    CONSTRAINT PAIS_PK PRIMARY KEY (id_pais)
);

/* =====================================================
   creamos la TABLA de TIPO_AUTOMOVIL
   ===================================================== */

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo CHAR(8) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT TIPO_AUTOMOVIL_PK PRIMARY KEY (id_tipo)
);


/* =====================================================
   creamos la TABLA MARCA
   ===================================================== */

CREATE TABLE MARCA (
    id_marca NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT MARCA_PK PRIMARY KEY (id_marca)
);


/* =====================================================
   creamos la TABLA SERVICIO
   ===================================================== */

CREATE TABLE SERVICIO (
    id_servicio NUMBER(3) NOT NULL,
    descripcion VARCHAR2(100) NOT NULL,
    costo NUMBER(7) NOT NULL,

    CONSTRAINT SERVICIO_PK PRIMARY KEY (id_servicio)
);

/* =====================================================
   creamos la TABLA CIUDAD
   ===================================================== */

CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3) NOT NULL,
    nom_ciudad VARCHAR2(20) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,

    CONSTRAINT CIUDAD_PK PRIMARY KEY (id_ciudad),
    CONSTRAINT CIUDAD_FK_PAIS FOREIGN KEY (cod_pais)
        REFERENCES PAIS (id_pais)
);


/* =====================================================
   creamos la TABLA MODELO
   ===================================================== */

CREATE TABLE MODELO (
    id_modelo NUMBER(3) NOT NULL,
    marca_id NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT MODELO_PK PRIMARY KEY (id_modelo),
    CONSTRAINT MODELO_FK_MARCA FOREIGN KEY (marca_id)
        REFERENCES MARCA (id_marca)
);


/* =====================================================
   creamos la TABLA CLIENTE
   ===================================================== */

CREATE TABLE CLIENTE (
    rut NUMBER(8) NOT NULL,
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    appaterno VARCHAR2(20) NOT NULL,
    apmaterno VARCHAR2(20) NOT NULL,
    telefono VARCHAR2(12),
    email VARCHAR2(40),
    tipo_cli CHAR(1) NOT NULL,

    CONSTRAINT CLIENTE_PK PRIMARY KEY (rut)
);
/* =====================================================
   creamos la TABLA SUCURSAL
   ===================================================== */

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3) NOT NULL,
    nom_sucursal VARCHAR2(20) NOT NULL,
    calle VARCHAR2(20) NOT NULL,
    num_calle NUMBER(4) NOT NULL,
    cod_ciudad NUMBER(3) NOT NULL,

    CONSTRAINT SUCURSAL_PK PRIMARY KEY (id_sucursal),
    CONSTRAINT SUCURSAL_FK_CIUDAD FOREIGN KEY (cod_ciudad)
        REFERENCES CIUDAD (id_ciudad)
);


/* =====================================================
   creamos la TABLA AUTOMOVIL
   ===================================================== */

CREATE TABLE AUTOMOVIL (
    patente CHAR(6) NOT NULL,
    anio NUMBER(4) NOT NULL,
    cant_puertas NUMBER(1) NOT NULL,
    km NUMBER(8) NOT NULL,
    color VARCHAR2(20) NOT NULL,
    cod_tipo_auto CHAR(8) NOT NULL,
    cod_modelo NUMBER(3) NOT NULL,
    rut_cliente NUMBER(8) NOT NULL,

    CONSTRAINT AUTOMOVIL_PK PRIMARY KEY (patente),

    CONSTRAINT AUTOMOVIL_FK_TIPO FOREIGN KEY (cod_tipo_auto)
        REFERENCES TIPO_AUTOMOVIL (id_tipo),

    CONSTRAINT AUTOMOVIL_FK_MODELO FOREIGN KEY (cod_modelo)
        REFERENCES MODELO (id_modelo),

    CONSTRAINT AUTOMOVIL_FK_CLIENTE FOREIGN KEY (rut_cliente)
        REFERENCES CLIENTE (rut)
);


/* =====================================================
   creamos la TABLA ESTANDAR
   ===================================================== */

CREATE TABLE ESTANDAR (
    p_dcto NUMBER(3) NOT NULL,
    puntaje_fidelidad NUMBER(4) NOT NULL,
    rut NUMBER(8) NOT NULL,

    CONSTRAINT ESTANDAR_PK PRIMARY KEY (rut),
    CONSTRAINT ESTANDAR_FK_CLIENTE FOREIGN KEY (rut)
        REFERENCES CLIENTE (rut)
);


/* =====================================================
   creamos la TABLA PREMIUM
   ===================================================== */

CREATE TABLE PREMIUM (
    p_dcto NUMBER(3) NOT NULL,
    peso_cliente NUMBER(4) NOT NULL,
    premio_cliente NUMBER(10) NOT NULL,
    rut NUMBER(8) NOT NULL,

    CONSTRAINT PREMIUM_PK PRIMARY KEY (rut),
    CONSTRAINT PREMIUM_FK_CLIENTE FOREIGN KEY (rut)
        REFERENCES CLIENTE (rut)
);

/* =====================================================
   creamos la TABLA MECANICO
   ===================================================== */

CREATE TABLE MECANICO (
    cod_mecanico NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 460 INCREMENT BY 7),

    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    appaterno VARCHAR2(20) NOT NULL,
    apmaterno VARCHAR2(20) NOT NULL,
    bono_jefatura NUMBER(10),
    sueldo NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor NUMBER(3),

    CONSTRAINT MECANICO_PK PRIMARY KEY (cod_mecanico),

    CONSTRAINT MECANICO_FK_SUPERVISOR
        FOREIGN KEY (cod_supervisor)
        REFERENCES MECANICO (cod_mecanico)
);

/* =====================================================
   creamos la TABLA MANTENCION
   ===================================================== */

CREATE TABLE MANTENCION (
    num_mantencion NUMBER(8) NOT NULL,
    cod_sucursal CHAR(3) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE,
    patente_auto CHAR(6),
    cod_mecanico NUMBER(3) NOT NULL,
    costo_total NUMBER(8) NOT NULL,
    estado VARCHAR2(15) NOT NULL,

    CONSTRAINT MANTENCION_PK
        PRIMARY KEY (num_mantencion),

    CONSTRAINT MANTENCION_FK_MECANICO
        FOREIGN KEY (cod_mecanico)
        REFERENCES MECANICO (cod_mecanico),

    CONSTRAINT MANTENCION_FK_AUTOMOVIL
        FOREIGN KEY (patente_auto)
        REFERENCES AUTOMOVIL (patente),

    CONSTRAINT MANTENCION_FK_SUCURSAL
        FOREIGN KEY (cod_sucursal)
        REFERENCES SUCURSAL (id_sucursal)
);

/* =====================================================
   creamos la TABLA DETALLE_SERVICIO
   ===================================================== */

CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(8) NOT NULL,
    cod_servicio NUMBER(3) NOT NULL,
    descuento_serv NUMBER(3) NOT NULL,
    cantidad NUMBER(2) NOT NULL,

    CONSTRAINT DETALLE_SERVICIO_PK
        PRIMARY KEY (mantencion_num, cod_servicio),

    CONSTRAINT DET_SERV_FK_MANTENCION
        FOREIGN KEY (mantencion_num)
        REFERENCES MANTENCION (num_mantencion),

    CONSTRAINT DET_SERV_FK_SERVICIO
        FOREIGN KEY (cod_servicio)
        REFERENCES SERVICIO (id_servicio)
);

/* =====================================================
   CASO 2: MODIFICACION DEL MODELO
   ===================================================== */

/* Eliminamos el atributo derivado costo_total de MANTENCION */

ALTER TABLE MANTENCION
DROP COLUMN costo_total;

/* Modificamos PK de MANTENCION y la relacion con DETALLE_SERVICIO */

/* Eliminamos la FK antigua */
ALTER TABLE DETALLE_SERVICIO
DROP CONSTRAINT DET_SERV_FK_MANTENCION;


/* 2. Eliminamos PK antigua de MANTENCION */
ALTER TABLE MANTENCION
DROP CONSTRAINT MANTENCION_PK;


/* 3. Creamos nueva PK compuesta de MANTENCION */
ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_PK
PRIMARY KEY (num_mantencion, cod_sucursal);


/* 4. Agregamos sucursal a DETALLE_SERVICIO */
ALTER TABLE DETALLE_SERVICIO
ADD cod_sucursal CHAR(3);


/* 5. Creamos nueva FK compuesta*/
ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT DET_SERV_FK_MANTENCION
FOREIGN KEY (mantencion_num, cod_sucursal)
REFERENCES MANTENCION (num_mantencion, cod_sucursal);

/* =====================================================
   RESTRICCIONES ADICIONALES
   ===================================================== */

/* Email de cliente debe ser unico */
ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_EMAIL_UK
UNIQUE (email);


/* DV solo puede ser 0-9 o K */
ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_DV_CK
CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));


/* Sueldo minimo de $510.000 */
ALTER TABLE MECANICO
ADD CONSTRAINT MECANICO_SUELDO_CK
CHECK (sueldo >= 510000);


/* Estados permitidos para mantencion */
ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_ESTADO_CK
CHECK (
    estado IN (
        'Reserva',
        'Ingresado',
        'Entregado',
        'Anulado'
    )
);

/* Hacemos obligatoria la sucursal en DETALLE_SERVICIO */

ALTER TABLE DETALLE_SERVICIO
MODIFY cod_sucursal CHAR(3) NOT NULL;

/* =====================================================
   CASO 3: POBLAMIENTO DEL MODELO
   ===================================================== */


/* Secuencia para los identificadores de SERVICIO */
CREATE SEQUENCE SEQ_SERVICIO
START WITH 400
INCREMENT BY 2
NOCYCLE;


/* Secuencia para los identificadores de CIUDAD */
CREATE SEQUENCE SEQ_CIUDAD
START WITH 165
INCREMENT BY 5
NOCYCLE;

/* =====================================================
   poblamiento de la TABLA PAIS
   ===================================================== */

INSERT INTO PAIS (nom_pais)
VALUES ('Chile');

INSERT INTO PAIS (nom_pais)
VALUES ('Peru');

INSERT INTO PAIS (nom_pais)
VALUES ('Colombia');

/* =====================================================
   poblamiento de la TABLA CIUDAD
   ===================================================== */

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (SEQ_CIUDAD.NEXTVAL, 'Santiago', 9);

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (SEQ_CIUDAD.NEXTVAL, 'Lima', 12);

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (SEQ_CIUDAD.NEXTVAL, 'Bogota', 15);

/* =====================================================
   poblamiento de la TABLA SUCURSAL
   ===================================================== */

INSERT INTO SUCURSAL
    (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES
    ('S01', 'Providencia', 'Av. A. Varas', 234, 165);

INSERT INTO SUCURSAL
    (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES
    ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);

INSERT INTO SUCURSAL
    (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES
    ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

/* =====================================================
   poblamiento de la TABLA SERVICIO
   ===================================================== */

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (SEQ_SERVICIO.NEXTVAL, 'Cambio Luces', 45000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (SEQ_SERVICIO.NEXTVAL, 'Desabolladura', 67000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (SEQ_SERVICIO.NEXTVAL, 'Revision Frenos', 30000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (SEQ_SERVICIO.NEXTVAL, 'Cambio Puerta Trasera', 50000);

/* =====================================================
   poblamiento de la TABLA MECANICO
   ===================================================== */

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Jorge', 'Pablo', 'Soto', 'Sierpe',
 5400000, 2759000, 223580, NULL);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Pedro', 'Jose', 'Manriquez', 'Corral',
 NULL, 759000, 23980, NULL);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Sandra', 'Josefa', 'Letelier', 'S.',
 NULL, 659000, 22358, 460);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Felipe', 'M.', 'Vidal', 'A.',
 NULL, 759000, 23580, 460);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Jose', 'Miguel', 'Troncoso', 'B.',
 NULL, 659000, 44580, 474);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Juan', 'Pablo', 'Sanchez', 'R.',
 NULL, 859000, 23380, 474);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Carlos', 'Felipe', 'Soto', 'J.',
 NULL, 597000, 23580, 474);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Alberto', 'P.', 'Cerda', 'Ramirez',
 NULL, 559000, 22380, 460);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Alejandra', 'Gabriela', 'Infanti', 'R.',
 NULL, 659000, 22380, 460);

INSERT INTO MECANICO
(pnombre, snombre, appaterno, apmaterno, bono_jefatura,
 sueldo, monto_impuestos, cod_supervisor)
VALUES
('Roberto', 'Patricio', 'Gutierrez', 'Sosa',
 NULL, 859000, 22380, 460);
 
/* =====================================================
   poblamiento de la TABLA MANTENCION
   ===================================================== */

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida,
 patente_auto, cod_mecanico, estado)
VALUES
(101, 'S01', TO_DATE('12-04-2023','DD-MM-YYYY'),
 NULL, NULL, 481, 'Reserva');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida,
 patente_auto, cod_mecanico, estado)
VALUES
(102, 'S02', TO_DATE('21-02-2023','DD-MM-YYYY'),
 TO_DATE('21-02-2023','DD-MM-YYYY'),
 NULL, 502, 'Entregado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida,
 patente_auto, cod_mecanico, estado)
VALUES
(103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'),
 NULL, NULL, 502, 'Anulado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida,
 patente_auto, cod_mecanico, estado)
VALUES
(104, 'S02', TO_DATE('11-08-2023','DD-MM-YYYY'),
 TO_DATE('18-08-2023','DD-MM-YYYY'),
 NULL, 509, 'Entregado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida,
 patente_auto, cod_mecanico, estado)
VALUES
(105, 'S03', TO_DATE('03-12-2023','DD-MM-YYYY'),
 NULL, NULL, 509, 'Ingresado');
 
COMMIT;

/* =====================================================
   CASO 4: RECUPERACION DE INFORMACION
   ===================================================== */
   
/* =====================================================
   Resultados del INFORME 1
   Simulacion de rebaja selectiva de impuestos
   ===================================================== */

SELECT
    cod_mecanico AS "ID MECANICO",
    pnombre || ' ' || appaterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO",
    monto_impuestos AS "IMPUESTO ACTUAL",
    ROUND(monto_impuestos * 0.80) AS "IMPUESTO REBAJADO",
    sueldo - ROUND(monto_impuestos * 0.80)
        AS "SUELDO CON REBAJA IMPUESTOS"
FROM MECANICO
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, appaterno ASC;

/* =====================================================
   Resultados del INFORME 2
   Calculo de reajuste salarial del 5%
   ===================================================== */

SELECT
    cod_mecanico AS "IDENTIFICADOR",
    pnombre || ' ' || snombre || ' ' || appaterno AS "MECANICO",
    sueldo AS "SALARIO ACTUAL",
    ROUND(sueldo * 0.05) AS "AJUSTE",
    sueldo + ROUND(sueldo * 0.05) AS "SUELDO_REAJUSTADO"
FROM MECANICO
WHERE sueldo BETWEEN 600000 AND 900000
   OR cod_supervisor IS NULL
ORDER BY sueldo ASC,
         pnombre || ' ' || snombre || ' ' || appaterno DESC;